repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        exclude: tools/
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ["--fix=auto"] # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

  # If you want to avoid flake8 errors due to unused vars or imports:
  - repo: https://github.com/myint/autoflake.git
    rev: v2.0.0
    hooks:
      - id: autoflake

  - repo: https://github.com/pycqa/isort
    rev: v5.11.3
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: ["click==8.0.4"] # Broken _unicodefun in later versions

  # If like to embrace black styles even in the docs:
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: ["black==21.9b0"] # Dependency on broken click (see black)

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        # You can add flake8 plugins via `additional_dependencies`:
        additional_dependencies:
          - flake8-bugbear

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "-j 0", # Run checks on muliple cores
            "--load-plugins=pylint.extensions.docparams,pylint.extensions.docstyle",
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
